#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${ssh_public_key}

package_update: true
package_upgrade: true
packages:
  - mc

runcmd:
  - echo '<html><body><h1>Welcome to LAMP server</h1><img src="https://storage.yandexcloud.net/${bucket_name}/image.jpg" alt="Bucket Image"></body></html>' > /var/www/html/index.html
